version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27018/hospital-db
      - PORT=5000

  frontend:
    build: ./FrontEnd
    ports:
      - "3000:80"
    depends_on:
      - backend

    mongo:
    image: mongo
    #ports:
      #- "27018:27019"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mongo-data:
