
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/hospital-db
      - PORT=5000

  frontend:
    build: ./FrontEnd
    ports:
      - "3000:80"
    depends_on:
      - backend
      
 healthcheck:
      test: bash -c "echo 'db.runCommand({ ping: 1 })' | mongo --quiet"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
