apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: keshava7259/backend-app
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/hospital-db
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapps
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
